/**
 * @a2ui-bridge/react-mantine - Icon Mapping
 *
 * Comprehensive icon mapping for Mantine/Tabler icons.
 * Maps semantic icon names to Tabler icon components.
 */

import React from 'react';
import {
  IconAlertCircle,
  IconCheck,
  IconCircleCheck,
  IconInfoCircle,
  IconAlertTriangle,
  IconX,
  IconPlus,
  IconMinus,
  IconEdit,
  IconTrash,
  IconSearch,
  IconSettings,
  IconUser,
  IconUsers,
  IconHeart,
  IconStar,
  IconDownload,
  IconUpload,
  IconShare,
  IconCopy,
  IconExternalLink,
  IconChevronRight,
  IconChevronLeft,
  IconChevronDown,
  IconChevronUp,
  IconArrowRight,
  IconArrowLeft,
  IconArrowUp,
  IconArrowDown,
  IconMenu2,
  IconHome,
  IconMail,
  IconPhone,
  IconCalendar,
  IconClock,
  IconMapPin,
  IconPhoto,
  IconFile,
  IconFolder,
  IconLock,
  IconEye,
  IconEyeOff,
  IconRefresh,
  IconSend,
  IconFilter,
  IconArrowsSort,
  IconCreditCard,
  IconWallet,
  IconCurrencyDollar,
  IconRun,
  IconTarget,
  IconList,
  IconDots,
  IconDotsVertical,
  IconBell,
  IconMessage,
  IconMessageCircle,
  IconPlayerPlay,
  IconPlayerPause,
  IconPlayerStop,
  IconVolume,
  IconVolumeOff,
  IconZoomIn,
  IconZoomOut,
  IconMaximize,
  IconMinimize,
  IconBookmark,
  IconTag,
  IconTags,
  IconFlag,
  IconPin,
  IconClipboard,
  IconArchive,
  IconBox,
  IconPackage,
  IconShoppingCart,
  IconGift,
  IconTruck,
  IconBriefcase,
  IconBuilding,
  IconSchool,
  IconCertificate,
  IconAward,
  IconTrophy,
  IconFlame,
  IconBolt,
  IconCloud,
  IconSun,
  IconMoon,
  IconWorld,
  IconGlobe,
  IconLanguage,
  IconCode,
  IconTerminal,
  IconBug,
  IconRocket,
  IconSparkles,
  IconWand,
  IconPalette,
  IconBrush,
  IconCamera,
  IconMicrophone,
  IconHeadphones,
  IconDevices,
  IconDeviceMobile,
  IconDeviceDesktop,
  IconPrinter,
  IconWifi,
  IconBluetooth,
  IconQrcode,
  IconFingerprint,
  IconShield,
  IconShieldCheck,
  IconKey,
  IconLogin,
  IconLogout,
  IconUserPlus,
  IconUserMinus,
  IconUserCheck,
  IconHelp,
  IconQuestionMark,
  IconExclamationMark,
  IconCircle,
  IconSquare,
  IconTriangle,
  IconHexagon,
  IconOctagon,
  IconInfinity,
  IconActivity,
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconGraph,
  IconTrendingUp,
  IconTrendingDown,
  IconPercentage,
  IconCalculator,
  IconReceipt,
  IconReportAnalytics,
  IconTable,
  IconLayoutGrid,
  IconLayoutList,
  IconLayoutKanban,
  IconLayoutDashboard,
} from '@tabler/icons-react';

/**
 * Icon mapping for dynamic icon rendering.
 * Maps semantic icon names to Tabler icon components.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const ICON_MAP: Record<string, React.ComponentType<any>> = {
  // Status & Alerts
  alert: IconAlertCircle,
  alertcircle: IconAlertCircle,
  check: IconCheck,
  checkcircle: IconCircleCheck,
  circlecheck: IconCircleCheck,
  checkmark: IconCheck,
  success: IconCircleCheck,
  info: IconInfoCircle,
  information: IconInfoCircle,
  warning: IconAlertTriangle,
  danger: IconAlertTriangle,
  error: IconAlertCircle,
  close: IconX,
  x: IconX,
  cancel: IconX,

  // Add/Remove
  plus: IconPlus,
  add: IconPlus,
  new: IconPlus,
  create: IconPlus,
  minus: IconMinus,
  remove: IconMinus,
  subtract: IconMinus,

  // Edit/Delete
  edit: IconEdit,
  pencil: IconEdit,
  modify: IconEdit,
  trash: IconTrash,
  delete: IconTrash,
  bin: IconTrash,

  // Search & Navigation
  search: IconSearch,
  find: IconSearch,
  magnify: IconSearch,
  menu: IconMenu2,
  hamburger: IconMenu2,
  bars: IconMenu2,
  home: IconHome,
  house: IconHome,
  external: IconExternalLink,
  externallink: IconExternalLink,
  link: IconExternalLink,
  openinnew: IconExternalLink,

  // Arrows & Chevrons
  chevronright: IconChevronRight,
  chevronleft: IconChevronLeft,
  chevrondown: IconChevronDown,
  chevronup: IconChevronUp,
  arrowright: IconArrowRight,
  arrowleft: IconArrowLeft,
  arrowup: IconArrowUp,
  arrowdown: IconArrowDown,
  next: IconChevronRight,
  previous: IconChevronLeft,
  back: IconArrowLeft,
  forward: IconArrowRight,

  // User & People
  user: IconUser,
  person: IconUser,
  profile: IconUser,
  account: IconUser,
  users: IconUsers,
  people: IconUsers,
  team: IconUsers,
  group: IconUsers,
  userplus: IconUserPlus,
  adduser: IconUserPlus,
  userminus: IconUserMinus,
  removeuser: IconUserMinus,
  usercheck: IconUserCheck,

  // Communication
  mail: IconMail,
  email: IconMail,
  envelope: IconMail,
  message: IconMessage,
  chat: IconMessageCircle,
  comment: IconMessageCircle,
  phone: IconPhone,
  call: IconPhone,
  telephone: IconPhone,
  send: IconSend,
  bell: IconBell,
  notification: IconBell,
  notifications: IconBell,

  // Actions
  settings: IconSettings,
  gear: IconSettings,
  cog: IconSettings,
  preferences: IconSettings,
  download: IconDownload,
  upload: IconUpload,
  share: IconShare,
  copy: IconCopy,
  duplicate: IconCopy,
  clipboard: IconClipboard,
  paste: IconClipboard,
  filter: IconFilter,
  sort: IconArrowsSort,
  refresh: IconRefresh,
  reload: IconRefresh,
  sync: IconRefresh,

  // Favorites & Actions
  heart: IconHeart,
  favorite: IconHeart,
  like: IconHeart,
  love: IconHeart,
  star: IconStar,
  rate: IconStar,
  rating: IconStar,
  bookmark: IconBookmark,
  save: IconBookmark,
  flag: IconFlag,
  report: IconFlag,
  pin: IconPin,

  // Time & Calendar
  calendar: IconCalendar,
  date: IconCalendar,
  schedule: IconCalendar,
  event: IconCalendar,
  clock: IconClock,
  time: IconClock,
  timer: IconClock,
  history: IconClock,

  // Location
  location: IconMapPin,
  mappin: IconMapPin,
  geopin: IconMapPin,
  address: IconMapPin,
  place: IconMapPin,
  world: IconWorld,
  globe: IconGlobe,
  global: IconGlobe,
  language: IconLanguage,
  translate: IconLanguage,

  // Files & Documents
  file: IconFile,
  document: IconFile,
  doc: IconFile,
  folder: IconFolder,
  directory: IconFolder,
  photo: IconPhoto,
  image: IconPhoto,
  picture: IconPhoto,
  camera: IconCamera,
  archive: IconArchive,

  // Security
  lock: IconLock,
  locked: IconLock,
  secure: IconLock,
  password: IconLock,
  key: IconKey,
  unlock: IconKey,
  shield: IconShield,
  security: IconShield,
  shieldcheck: IconShieldCheck,
  verified: IconShieldCheck,
  fingerprint: IconFingerprint,
  biometric: IconFingerprint,

  // View & Visibility
  eye: IconEye,
  view: IconEye,
  show: IconEye,
  visible: IconEye,
  eyeoff: IconEyeOff,
  hide: IconEyeOff,
  hidden: IconEyeOff,
  invisible: IconEyeOff,
  zoomin: IconZoomIn,
  zoomout: IconZoomOut,
  maximize: IconMaximize,
  fullscreen: IconMaximize,
  minimize: IconMinimize,

  // Media
  play: IconPlayerPlay,
  pause: IconPlayerPause,
  stop: IconPlayerStop,
  volume: IconVolume,
  sound: IconVolume,
  audio: IconVolume,
  mute: IconVolumeOff,
  volumeoff: IconVolumeOff,
  microphone: IconMicrophone,
  mic: IconMicrophone,
  headphones: IconHeadphones,

  // Money & Commerce
  creditcard: IconCreditCard,
  card: IconCreditCard,
  payment: IconCreditCard,
  wallet: IconWallet,
  money: IconCurrencyDollar,
  dollar: IconCurrencyDollar,
  currency: IconCurrencyDollar,
  price: IconCurrencyDollar,
  cart: IconShoppingCart,
  shoppingcart: IconShoppingCart,
  basket: IconShoppingCart,
  gift: IconGift,
  present: IconGift,
  receipt: IconReceipt,
  invoice: IconReceipt,

  // Shipping & Logistics
  truck: IconTruck,
  delivery: IconTruck,
  shipping: IconTruck,
  box: IconBox,
  package: IconPackage,
  parcel: IconPackage,

  // Work & Business
  briefcase: IconBriefcase,
  work: IconBriefcase,
  job: IconBriefcase,
  business: IconBriefcase,
  building: IconBuilding,
  company: IconBuilding,
  office: IconBuilding,

  // Education & Achievement
  school: IconSchool,
  education: IconSchool,
  learning: IconSchool,
  certificate: IconCertificate,
  diploma: IconCertificate,
  award: IconAward,
  medal: IconAward,
  trophy: IconTrophy,
  winner: IconTrophy,
  achievement: IconTrophy,

  // Activity & Sports
  running: IconRun,
  run: IconRun,
  exercise: IconRun,
  fitness: IconRun,
  activity: IconActivity,
  target: IconTarget,
  goal: IconTarget,
  aim: IconTarget,
  bullseye: IconTarget,
  flame: IconFlame,
  fire: IconFlame,
  hot: IconFlame,
  trending: IconFlame,

  // Energy & Power
  bolt: IconBolt,
  lightning: IconBolt,
  power: IconBolt,
  electricity: IconBolt,
  energy: IconBolt,

  // Weather & Nature
  cloud: IconCloud,
  weather: IconCloud,
  sun: IconSun,
  light: IconSun,
  brightness: IconSun,
  moon: IconMoon,
  dark: IconMoon,
  night: IconMoon,

  // Tech & Development
  code: IconCode,
  developer: IconCode,
  programming: IconCode,
  terminal: IconTerminal,
  console: IconTerminal,
  command: IconTerminal,
  bug: IconBug,
  debug: IconBug,
  issue: IconBug,
  rocket: IconRocket,
  launch: IconRocket,
  startup: IconRocket,
  deploy: IconRocket,
  sparkles: IconSparkles,
  magic: IconSparkles,
  ai: IconSparkles,
  wand: IconWand,
  generate: IconWand,

  // Design & Creative
  palette: IconPalette,
  colors: IconPalette,
  theme: IconPalette,
  brush: IconBrush,
  paint: IconBrush,
  design: IconBrush,

  // Devices
  devices: IconDevices,
  mobile: IconDeviceMobile,
  smartphone: IconDeviceMobile,
  desktop: IconDeviceDesktop,
  computer: IconDeviceDesktop,
  laptop: IconDeviceDesktop,
  printer: IconPrinter,
  print: IconPrinter,
  wifi: IconWifi,
  wireless: IconWifi,
  internet: IconWifi,
  bluetooth: IconBluetooth,
  qrcode: IconQrcode,
  qr: IconQrcode,
  scan: IconQrcode,

  // Auth
  login: IconLogin,
  signin: IconLogin,
  logout: IconLogout,
  signout: IconLogout,

  // Help & Support
  help: IconHelp,
  support: IconHelp,
  questionmark: IconQuestionMark,
  question: IconQuestionMark,
  exclamationmark: IconExclamationMark,
  exclamation: IconExclamationMark,
  important: IconExclamationMark,

  // List & Organization
  list: IconList,
  listing: IconList,
  items: IconList,
  dots: IconDots,
  more: IconDots,
  ellipsis: IconDots,
  options: IconDotsVertical,
  dotsvertical: IconDotsVertical,
  tag: IconTag,
  label: IconTag,
  tags: IconTags,
  labels: IconTags,

  // Shapes
  circle: IconCircle,
  square: IconSquare,
  triangle: IconTriangle,
  hexagon: IconHexagon,
  octagon: IconOctagon,
  infinity: IconInfinity,
  infinite: IconInfinity,

  // Charts & Analytics
  chart: IconChartBar,
  chartbar: IconChartBar,
  barchart: IconChartBar,
  analytics: IconChartBar,
  chartline: IconChartLine,
  linechart: IconChartLine,
  chartpie: IconChartPie,
  piechart: IconChartPie,
  graph: IconGraph,
  trendingup: IconTrendingUp,
  increase: IconTrendingUp,
  growth: IconTrendingUp,
  trendingdown: IconTrendingDown,
  decrease: IconTrendingDown,
  decline: IconTrendingDown,
  percentage: IconPercentage,
  percent: IconPercentage,
  calculator: IconCalculator,
  calculate: IconCalculator,
  math: IconCalculator,
  reportanalytics: IconReportAnalytics,
  reports: IconReportAnalytics,
  table: IconTable,
  spreadsheet: IconTable,
  grid: IconTable,

  // Layout
  layoutgrid: IconLayoutGrid,
  gridview: IconLayoutGrid,
  layoutlist: IconLayoutList,
  listview: IconLayoutList,
  layoutkanban: IconLayoutKanban,
  kanban: IconLayoutKanban,
  board: IconLayoutKanban,
  layoutdashboard: IconLayoutDashboard,
  dashboard: IconLayoutDashboard,
};

/**
 * Helper to get icon component from semantic name.
 * Normalizes the name by removing dashes, underscores, and spaces.
 */
export const getIcon = (iconName?: string) => {
  if (!iconName) return null;
  const normalized = iconName.toLowerCase().replace(/[-_\s]/g, '');
  return ICON_MAP[normalized] || ICON_MAP[iconName] || null;
};

// Re-export commonly used icons for convenience
export {
  IconAlertCircle,
  IconCheck,
  IconCircleCheck,
  IconInfoCircle,
  IconAlertTriangle,
  IconX,
} from '@tabler/icons-react';
